services:
  postgres:
    container_name: postgres
    image: postgres:latest

    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}

    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"

    restart: always

  promos:
    container_name: service-promos

    build: ./service

    environment:
      - SERVER_NETWORK=${SERVER_NETWORK:-tcp}
      - SERVER_PORT=${SERVER_PORT:-3000}

      - DB_HOST=${POSTGRES_HOST:-postgres}
      - DB_PORT=${POSTGRES_PORT:-5432}
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-5}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-3}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-mAz0H1zm}
      - DB_NAME=${POSTGRES_DB:-postgres}

      - SERVICE_USERS_HOST=${SERVICE_USERS_HOST:-localhost}
      - SERVICE_USERS_PORT=${SERVICE_USERS_PORT:-1488}

    ports:
     - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"

    depends_on:
     - postgres