services:
  postgres:
    container_name: postgres
    image: postgres:latest

    environment:
      - POSTGRES_USER=${POSTGRES_USER:-}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - POSTGRES_DB=${POSTGRES_DB:-}

    ports:
      - "${POSTGRES_PORT:-}:${POSTGRES_PORT:-}"

    restart: always

  promos:
    container_name: service-promos

    build: ./service

    environment:
      - SERVER_NETWORK=${SERVER_NETWORK:-}
      - SERVER_PORT=${SERVER_PORT:-}

      - DB_HOST=${POSTGRES_HOST:-}
      - DB_PORT=${POSTGRES_PORT:-}
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-}
      - DB_USER=${POSTGRES_USER:-}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-}
      - DB_NAME=${POSTGRES_DB:-}

      - SERVICE_USERS_HOST=${SERVICE_USERS_HOST:-}
      - SERVICE_USERS_PORT=${SERVICE_USERS_PORT:-}

    ports:
     - "${SERVER_PORT:-}:${SERVER_PORT:-}"

    depends_on:
     - postgres
