services:
  postgres:
    container_name: postgres-go
    image: postgres:latest
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${DB_USER:-}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-}
      - POSTGRES_DB=${DB_NAME:-}

    ports:
      - "${DB_PORT:-}:${DB_PORT:-}"

    restart: always

  warns:
    container_name: service-warns

    build: ./

    environment:
      - SERVER_NETWORK=tcp
      - SERVER_PORT=${SERVICE_WARNS_PORT:-}

      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-}

      - SERVICE_USERS_HOST=localhost
      - SERVICE_USERS_PORT=${SERVICE_USERS_PORT:-}

      - HASH_SALT=${HASH_SALT:-}
      - WARNS_BEFORE_BAN=${WARNS_BEFORE_BAN:-}

    ports:
     - "${SERVICE_WARNS_PORT:-}:${SERVICE_WARNS_PORT:-}"

    command: "/warns"

  promos:
    container_name: service-promos

    build: ./

    environment:
      - SERVER_NETWORK=tcp
      - SERVER_PORT=${SERVICE_PROMOS_PORT:-}

      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-}

      - SERVICE_USERS_HOST=localhost
      - SERVICE_USERS_PORT=${SERVICE_USERS_PORT:-}
  
      - HASH_SALT=${HASH_SALT:-}
      - WARNS_BEFORE_BAN=${WARNS_BEFORE_BAN:-}

    ports:
     - "${SERVICE_PROMOS_PORT:-}:${SERVICE_PROMOS_PORT:-}"

    command: "/promos"

  checks:

    container_name: service-checks

    build: ./

    environment:
      - SERVER_NETWORK=tcp
      - SERVER_PORT=${SERVICE_CHECKS_PORT:-}

      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-}

      - SERVICE_USERS_HOST=localhost
      - SERVICE_USERS_PORT=${SERVICE_USERS_PORT:-}

      - HASH_SALT=${HASH_SALT:-}
      - WARNS_BEFORE_BAN=${WARNS_BEFORE_BAN:-}

    ports:
     - "${SERVICE_CHECKS_PORT:-}:${SERVICE_CHECKS_PORT:-}"

    command: "/checks"