services:
  postgres:
    container_name: postgres-warns
    image: postgres:latest

    environment:
      - POSTGRES_USER=${DB_USER:-}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-}
      - POSTGRES_DB=${DB_NAME:-}

    ports:
      - "${DB_PORT:-}:${DB_PORT:-}"

    restart: always

  warns:
    container_name: service-warns

    build: ./

    environment:
      - SERVER_NETWORK=tcp
      - SERVER_PORT=${SERVICE_WARNS_PORT:-}

      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-}

      - SERVICE_USERS_HOST=localhost
      - SERVICE_USERS_PORT=${SERVICE_USERS_PORT:-}

      - WARNS_BEFORE_BAN=${WARNS_BEFORE_BAN:-}

    ports:
     - "${SERVICE_WARNS_PORT:-}:${SERVICE_WARNS_PORT:-}"

    depends_on:
     - postgres-warns